spring:
  data:
    mongodb:
      uri: mongodb+srv://mongoUser:Mongo123234545@cluster0.qgwt5fo.mongodb.net/products
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka