spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: test
    password: test
    hikari:
      connectionTimeout: 2000
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service
server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
